# NUMPY

NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a vast amount of high-level mathematical functions operate on these matric

#### Arrays can store data very compactly and are more efficient for storing large amounts of data. Arrays are great for numerical operations; lists cannot directly handle math operations

# Difference Btwn List and array

#### A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

#### A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

# In List we can pass different datatypes but in array we can only give similar Datatypes

# Creating Array

In [1]:
import numpy as np

In [6]:
#with list
# arr = np.array([1,2,4,6,8])

# arr
# arr0 = np.array([1,2,3,4,5])
# arr0
arr1 = np.array((1,2,3,6,7,8))
arr1

array([1, 2, 3, 6, 7, 8])

In [7]:
#check data type
type(arr1)

numpy.ndarray

In [8]:
# with tuple
arr = np.array((1, 2, 3, 4, 5))

arr

array([1, 2, 3, 4, 5])

In [9]:
a = [1,2,3,4]
b = [5,6,7,8]
arry_1 = np.array([a,b])
arry_1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# np.zeros((2,3) , dtype=int)
# np.ones((2,3) , dtype=int)
# np.empty((2,3) , dtype=int)

array([[100765971626705,               0,     -4294967295],
       [              0,               0,               0]])

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
#add list into np
lis=[1,2,4,6,8]

arr=np.array(lis)
arr

array([1, 2, 4, 6, 8])

In [16]:
arr


array([1, 2, 4, 6, 8])

In [17]:
#Return a new array of given shape and type, with random values..


a = np.empty([2,2], dtype = int)
a

array([[100765966564225,               0],
       [             56, 138465857903840]])

In [18]:
#The numpy.ones() function returns a new array of given shape and type, with ones.
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [19]:
a = np.zeros((5,2), dtype = int)
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [20]:
#create array with ones
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
#create array with range
a = np.arange(4)
a

array([0, 1, 2, 3])

 Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop,step)

In [ ]:
#with condition
a = np.arange(10,30,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [23]:
# #using line space, number of sample =5
# a = np.linspace(10,30,5)
# a
a = np.linspace(1,20,3)
a

array([ 1. , 10.5, 20. ])

# Dimension

In [24]:
#Zero dimension
arr = np.array(42)

print(arr)

print(arr.ndim)

42
0


In [25]:
#one dimension
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(arr.ndim)

[1 2 3 4 5]
1


More than one dimension:

In [32]:
# #Two dimension

# arr = np.array([[1, 2, 3], [4, 5, 6]])

# print(arr)
# print(arr.ndim)

arry = np.array([[1,2,3,4],[2,3,4,6],[22,33,44,55]])
print(arry)
print(arry.ndim)

[[ 1  2  3  4]
 [ 2  3  4  6]
 [22 33 44 55]]
2


In [33]:
#Three dimension

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [35]:
# #multiple dimension
# arr = np.array([1, 2, 3, 4], ndmin=5)

# print(arr)
# print(arr.ndim)

arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [43]:
#random method to creat array
a = np.random.rand()
a

0.46377418415529115

Random sampling in numpy | randint() function

In [47]:
a = np.random.randint(20, size=(5))

a

array([17,  3,  0, 13, 15])

In [48]:
a = np.random.rand(4)

a

array([0.48590254, 0.35057908, 0.18768789, 0.69010641])

In [49]:
a = np.random.rand(2,2)

a


array([[0.14824406, 0.38001492],
       [0.73986977, 0.21200521]])

Return one of the values in an array:

In [54]:

dice = np.random.choice([1,2,3,4,5,6])

dice

1

Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)

In [95]:
# a = np.random.choice([3, 5, 7, 9], size=(1, 2))

# a
a = np.random.choice([10,20,30,40,50,60], size=(1,2))
a
b = np.random.choice([1,2,3,4,5],size=(1,2))
b

array([[4, 3]])

# Data type

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [67]:
#int
arr = np.array([1,2,3,4,5])

print(arr.dtype)

int64


In [68]:
#string
arr = np.array(['python', 'java', 'c'])

print(arr.dtype)

<U6


In [86]:
#convert data type
import datetime
arr = np.array([1,2,3,4,5.8])

#arr.dtype
new_arr = arr.astype('i')
new_arr

array([1, 2, 3, 4, 5], dtype=int32)

In [87]:
print(arr)
print(new_arr)
print(new_arr.dtype)

[1.  2.  3.  4.  5.8]
[1 2 3 4 5]
int32


In [88]:
arr = np.array([4, 0, 2])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# COPY Array

In [99]:
a = np.array([[1,2,3,4],[2,3,4,5]])
a
print('a is :\n',a)
b = a.copy()
print('b is :\n',b)

a is :
 [[1 2 3 4]
 [2 3 4 5]]
b is :
 [[1 2 3 4]
 [2 3 4 5]]


In [100]:
arr = np.array([10,20,30,40,50])
a = arr.copy()

In [101]:
print(arr)
print(a)

[10 20 30 40 50]
[10 20 30 40 50]


Make a view, change the original array, and display both arrays

In [112]:
#view, changing in view array affect orignal arrray

arr = np.array([10,20,30,40,50])
a = arr.view()
print("before\n")
print("arr is :\n",arr)
print("a is :\n",a)
a[0]=50
print("\nafter\n")
print("arr is :\n",arr)
print("a is :\n",a)

before

arr is :
 [10 20 30 40 50]
a is :
 [10 20 30 40 50]

after

arr is :
 [50 20 30 40 50]
a is :
 [50 20 30 40 50]


In [113]:
print(arr)
print(a)

[50 20 30 40 50]
[50 20 30 40 50]


# Indexing & slicing

In [114]:
arr = np.array([10,20,30,40,50])

arr[0]

10

In [115]:

arr[1]

20

In [121]:
import numpy as np
arr = np.array([[10,20,30,40,50], [60,70,80,90,100],[110,120,130,140,150]])
print(arr)
print("arr[1, 3]:\n",arr[1, 3])
print("arr[-2, -2]:\n",arr[-2, -2])

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
arr[1, 3]:
 90
arr[-2, -2]:
 90


In [119]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
arr[0, -2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


4

In [126]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [127]:
arr[:2,:3]


array([[1, 2, 3],
       [2, 3, 4]])

In [128]:
arr[2:,3:]


array([[8, 9]])

In [129]:
arr[:,3:]


array([[4, 5],
       [5, 6],
       [8, 9]])

# Shape

In [133]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.shape

(2, 4)

In [134]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
arr.shape


[[[1 2 3 4]]]


(1, 1, 4)

# Reshape

In [137]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

print("     ")

new_arr = arr.reshape(4,3)

print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
     
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [143]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

newarr = arr.reshape(2, 2, 3)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [147]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr
arr.transpose()#arr.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# iterating

In [149]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# for i in arr:
#   print(i)
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [150]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [156]:
# for i in np.nditer(arr):
#    print(i)
for i in np.nditer(arr):
   print(i)

1
2
3
4
5
2
3
4
5
6
9
7
6
8
9


In [157]:


# Create two arrays with different shapes
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([2, 3, 4])

# Create an nditer object to iterate over both arrays simultaneously
it = np.nditer([a, b])

# Iterate over elements and perform some operation (e.g., addition)
for x, y in it:
    print(x + y)


3
5
7
6
8
10


# Transpose  array

rotate array

In [158]:

print(arr)

print("__________")

Tran_arry  = arr.T

print(Tran_arry)


[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
__________
[[1 2 9]
 [2 3 7]
 [3 4 6]
 [4 5 8]
 [5 6 9]]


# sorting

In [159]:
arr = np.array([7,2,23,15,11])
print(arr)
print(np.sort(arr))

[ 7  2 23 15 11]
[ 2  7 11 15 23]


In [161]:
#two dim array sort
arr = np.array([[20,10], [13,7]])
new_arr = np.sort(arr)
new_arr

array([[10, 20],
       [ 7, 13]])

In [164]:
#sorting by axis , row ,column
arr = np.array([[20,10], [3,7]])
print(arr)
new_arr = np.sort(arr, axis = 0)
new_arr

[[20 10]
 [ 3  7]]


array([[ 3,  7],
       [20, 10]])

# Searching

In [172]:
# arr = np.array([[2,2,5,7,8,2,5,9,2,3,4,2,0,2],[2,3,2,3,4,5,2,5,6,7,2,3,4,2]])
arr = np.array([2,2,5,7,8,2,5,9,2,3,4,2,0,2])
# x = np.where(arr == 2)
x = np.where(arr == 2)
print(x)

(array([ 0,  1,  5,  8, 11, 13]),)


# Splitting

In [177]:
arr = np.array([2,2,5,7,8,2,5,9])

#newarr = np.array_split(arr, 4)
newarr = np.array_split(arr,3)
print(newarr)


[array([2, 2, 5]), array([7, 8, 2]), array([5, 9])]


# joining

In [182]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

# arr = np.concatenate((arr, arr1))
arr = np.concatenate((arr1,arr))
arr

array([ 8, 10, 12,  2,  4,  6])

In [183]:
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=0)

arr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [184]:
#try with 1
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=1)

arr

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [ ]:
arr = np.array([[2,4,6],[22,33,44]])

arr1 = np.array([[8,10,12],[20,30,40]])

arr = np.hstack((arr, arr1))

arr

In [187]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.hstack((arr, arr1))

arr


array([ 2,  4,  6,  8, 10, 12])

In [188]:

arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.vstack((arr, arr1))

arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [189]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


arr = np.dstack((arr, arr1))

arr

array([[[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

# String , arithmmetic , static opration

In [190]:
np.char.add(['hello','word'],['!','?'])

array(['hello!', 'word?'], dtype='<U6')

In [196]:
arr = np.array(["USA","INDIA","RUSSIA"])

new_arr = np.char.lower(arr)

print(new_arr)
new_arr=np.char.upper(new_arr)
print(new_arr)

['usa' 'india' 'russia']
['USA' 'INDIA' 'RUSSIA']


In [199]:
arr= np.char.join('-', 'chirag')
arr

array('c-h-i-r-a-g', dtype='<U11')

In [202]:
np.char.split(['hello word'])

array([list(['hello', 'word'])], dtype=object)

In [203]:
np.char.replace(['hello word'],'o','a')

array(['hella ward'], dtype='<U10')

In [204]:
np.char.strip([' hello word  '])

array(['hello word'], dtype='<U13')

In [205]:
np.char.join('-',['hello word'])

array(['h-e-l-l-o- -w-o-r-d'], dtype='<U19')

In [206]:
np.char.capitalize(['hello word'])

array(['Hello word'], dtype='<U10')

In [211]:
np.char.count(['hello word'],'w')

array([1])

In [213]:
np.char.isnumeric(['123','hello word','44','toy'])

array([ True, False,  True, False])

In [218]:
arr = np.array([2.344,6.232,8.34,5,3.5799,4.36])

np.around(arr,2)

array([2.34, 6.23, 8.34, 5.  , 3.58, 4.36])

In [219]:
np.around(arr, decimals = 1)

array([2.3, 6.2, 8.3, 5. , 3.6, 4.4])

In [221]:
# np.floor(arr)
np.ceil(arr)

array([3., 7., 9., 5., 4., 5.])

In [222]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


In [223]:
np.add(arr,arr1)

array([10, 14, 18])

In [224]:
np.subtract(arr,arr1)

array([-6, -6, -6])

In [225]:
np.multiply(arr,arr1)

array([16, 40, 72])

In [226]:
np.divide(arr1,arr)

array([4. , 2.5, 2. ])

In [227]:
np.power(arr,2)

array([ 4, 16, 36])

In [228]:
np.mod(arr1,arr)

array([0, 2, 0])

In [233]:
arr = np.array([10, 22, 34, 4,55, 6, 97, 83, 93, 120, 111, 12])
arr

array([ 10,  22,  34,   4,  55,   6,  97,  83,  93, 120, 111,  12])

In [237]:
# np.median(arr)
np.sum(arr)

647

In [235]:
np.mean(arr)

53.916666666666664

In [236]:
np.average(arr)

53.916666666666664

In [238]:
np.std(arr)

42.56849056390054

In [239]:
np.var(arr)

1812.0763888888894

In [240]:
np.sqrt([4,16,49])

array([2., 4., 7.])